### ISSUE TITLE
Possible issue with keepalive

### ISSUE THREAD

**Issue by GeertHauwaerts** [teamreflex/DiscordPHP#106]
Hi there,

[My bot](https://gist.github.com/GeertHauwaerts/059adbc38fbac317b78c5a3a886c5562) disconnects frequently (+/- every hour) with the message `Tried to write to closed stream.`.

Could it be an issue with the keepalive that the Discord API expects?

```
api@VCC-API001:~$ vccd
[26-04-2016 22:02:39] Connected to the Discord API.
[26-04-2016 22:53:54] Error: exception 'RuntimeException' with message 'Tried to write to closed stream.' in /var/www/vendor/react/stream/src/Buffer.php:108
Stack trace:
#0 [internal function]: React\Stream\Buffer->handleWrite(Resource id #147, Object(React\EventLoop\StreamSelectLoop))
#1 /var/www/vendor/react/event-loop/src/StreamSelectLoop.php(240): call_user_func(Array, Resource id #147, Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(4895681.142807)
#3 /var/www/vendor/team-reflex/discord-php/src/Discord/WebSockets/WebSocket.php(916): React\EventLoop\StreamSelectLoop->run()
#4 /var/www/backend/vccd(130): Discord\WebSockets\WebSocket->run()
#5 {main}
api@VCC-API001:~$ 
```

PS: I am using `"team-reflex/discord-php": "dev-develop"`

**Comment by uniquoooo** [comment]
Currently trying to fix this but not sure what is causing this.

**Comment by GeertHauwaerts** [comment]
I checked my logs and the problem is still here (see below); I compared the `Error` timestamps with the timestamps I sent messages to Discord, they do not match.

So I assume most of the errors here are caused by a failed keepalive, or any other message the library passively sends over the websocket.

```
root@VCC-API001:~# tail -n 1000 /var/log/vccd.log | grep -v Added | grep -v Whoop | grep -v Removed | tail -n 20
[17-05-2016 18:48:40] Error: Tried to write to closed stream.
[17-05-2016 18:49:58] Error: Tried to write to closed stream.
[17-05-2016 18:52:15] Error: Tried to write to closed stream.
[17-05-2016 18:53:02] Connected to the Discord API.
PHP Warning:  stream_get_contents(): SSL: Connection reset by peer in /var/www/vendor/react/socket-client/src/SecureStream.php on line 46
PHP Warning:  stream_get_contents(): SSL: Connection reset by peer in /var/www/vendor/react/socket-client/src/SecureStream.php on line 46
[19-05-2016 05:15:28] Error: Tried to write to closed stream.
[19-05-2016 05:16:02] Connected to the Discord API.
[19-05-2016 05:20:40] Error: Tried to write to closed stream.
[19-05-2016 05:21:02] Connected to the Discord API.
[19-05-2016 05:45:17] Error: Tried to write to closed stream.
[19-05-2016 05:46:02] Connected to the Discord API.
[23-05-2016 18:08:54] Error: Tried to write to closed stream.
[23-05-2016 18:09:18] Connected to the Discord API.
PHP Warning:  stream_get_contents(): SSL: Connection timed out in /var/www/vendor/react/socket-client/src/SecureStream.php on line 46
[24-05-2016 21:46:25] Error: Tried to write to closed stream.
[24-05-2016 21:47:03] Connected to the Discord API.
[25-05-2016 17:55:40] Connected to the Discord API.
[26-05-2016 00:48:33] Error: Tried to write to closed stream.
[26-05-2016 00:49:02] Connected to the Discord API.
root@VCC-API001:~#
```

**Comment by uniquoooo** [comment]
The `Tried to write to closed stream` is an issue with the WebSocket library, it is currently being fixed. I can't do **much** about the heartbeat thing but v4 will fix it completely.

**Comment by GeertHauwaerts** [comment]
Awesome, I'll just wait until v4. For now I just run the bot with a crontab that check whether it died and instantly restarts it.

**Comment by uniquoooo** [comment]
V4 being released.
