### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by shibdib** [teamreflex/DiscordPHP#152]
See below for 2 common ssl errors that cause the bot to crash. The second one I believe is discord acting up but the first seems bot related.

```
[2016-09-08 09:15:59] Dramiel.ERROR: exception 'ErrorException' with message 'fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:140D00CF:SSL routines:SSL_write:protocol is shutdown' in /home/Dramiel/mamba/vendor/react/stream/src/Buffer.php:86 Stack trace: #0 [internal function]: React\Stream\Buffer->handleWrite(Resource id #182, Object(React\EventLoop\StreamSelectLoop)) #1 /home/Dramiel/mamba/vendor/react/event-loop/src/StreamSelectLoop.php(240): call_user_func(Array, Resource id #182, Object(React\EventLoop\StreamSelectLoop)) #2 /home/Dramiel/mamba/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(0) #3 /home/Dramiel/mamba/vendor/team-reflex/discord-php/src/Discord/Discord.php(1223): React\EventLoop\StreamSelectLoop->run() #4 /home/Dramiel/mamba/Dramiel.php(214): Discord\Discord->run() #5 {main} [] []
```

````
[2016-09-08 10:40:04] Dramiel.ERROR: exception 'DomainException' with message 'HTTP/1.1 525 Origin SSL Handshake Error Date: Thu, 08 Sep 2016 15:40:04 GMT Content-Type: text/html; charset=UTF-8 Transfer-Encoding: chunked Connection: keep-alive Set-Cookie: __cfduid=da8917f3fa950c0308ae6d1770e3196871473349196; expires=Fri, 08-Sep-17 15:39:56 GMT; path=/; domain=.discord.gg; HttpOnly Expires: Thu, 01 Jan 1970 00:00:01 GMT Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0 Pragma: no-cache X-Frame-Options: SAMEORIGIN Server: cloudflare-nginx CF-RAY: 2df37efcf45458d9-DFW  164d <!DOCTYPE html> <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]--> <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]--> <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]--> <!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]--> <head> <meta http-equiv="refresh" content="0">  <meta http-equiv="set-cookie" content="cf_use_ob=443; expires=Thu, 08-Sep-16 15:40:34 GMT; path=/">  <meta http-equiv="set-cookie" content="cf_ob_info=525:2df37efcf45458d9:DFW; expires=Thu, 08-Sep-16 15:40:34 GMT; path=/">   <title>gateway.discord.gg | 525: SSL handshake failed</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" /> <!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]--> <style type="text/css">body{margin:0;padding:0}</style> <!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]--> <!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]--> <script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>  </head> <body> <div id="cf-wrapper">            <div id="cf-error-details" class="cf-error-details-wrapper">         <div class="cf-wrapper cf-error-overview">             <h1>               <span class="cf-error-type" data-translate="error">Error</span>               <span class="cf-error-code">525</span>               <small class="heading-ray-id">Ray ID: 2df37efcf45458d9 &bull; 2016-09-08 15:40:04 UTC</small>             </h1>             <h2 class="cf-subheadline" data-translate="error_desc">SSL handshake failed</h2>         </div><!-- /.error-overview -->          <div class="cf-section cf-highlight cf-status-display">             <div class="cf-wrapper">                 <div class="cf-columns cols-3">                    <div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">   <div class="cf-icon-error-container">     <i class="cf-icon cf-icon-browser"></i>     <i class="cf-icon-status cf-icon-ok"></i>   </div>   <span class="cf-status-desc" data-translate="browser_desc">You</span>   <h3 class="cf-status-name" data-translate="browser_label">Browser</h3>   <span class="cf-status-label" data-translate="browser_status_label">Working</span> </div>  <div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">   <div class="cf-icon-error-container">     <i class="cf-icon cf-icon-cloud"></i>     <i class="cf-icon-status cf-icon-ok"></i>   </div>   <span class="cf-status-desc" data-translate="cloud_desc">Dallas</span>   <h3 class="cf-status-name" data-translate="cloud_label">CloudFlare</h3>   <span class="cf-status-label" data-translate="cloud_status_label">Working</span> </div>  <div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">   <div class="cf-icon-error-container">     <i class="cf-icon cf-icon-server"></i>     <i class="cf-icon-status cf-icon-error"></i>   </div>   <span class="cf-status-desc" data-translate="server_desc">gateway.discord.gg</span>   <h3 class="cf-status-name" data-translate="server_label">Host</h3>   <span class="cf-status-label" data-translate="server_status_label">Error</span> </div>                  </div>             </div>         </div><!-- /.status-display -->          <div class="cf-section cf-wrapper">             <div class="cf-columns two">                 <div class="cf-column">                     <h2 data-translate="what_happened">What happened?</h2>                     <p data-translate="origin_ssl_bad_handshake">CloudFlare is unable to establish an SSL connection to the origin server.</p>                 </div>                  <div class="cf-column">                     <h2 data-translate="what_can_i_do">What can I do?</h2>                           <h5 data-translate="if_website_visitor">If you're a visitor of this website:</h5>       <p data-translate="try_again_in_a_few">Please try again in a few minutes.</p>        <h5 data-translate="if_website_owner">If you're the owner of this website:</h5>       <p><span data-translate="525_owner_desc">It appears that the SSL configuration used is not compatible with CloudFlare. This could happen for a several reasons, including no shared cipher suites.</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200278659">Additional troubleshooting information here.</a></p>                 </div>             </div>         </div><!-- /.section -->          <div class="cf-error-footer cf-wrapper">   <p>     <span class="cf-footer-item">CloudFlare Ray ID: <strong>2df37efcf45458d9</strong></span>     <span class="cf-footer-separator">&bull;</span>     <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 204.12.202.26</span>     <span class="cf-footer-separator">&bull;</span>     <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">CloudFlare</a></span>        </p> </div><!-- /.error-footer -->       </div><!-- /#cf-error-details --> </div><!-- /#cf-wrapper -->  0  ' in /home/Dramiel/mamba/vendor/ratchet/pawl/src/Connector.php:73 Stack trace: #0 [internal function]: Ratchet\Client\Connector->Ratchet\Client\{closure}('HTTP/1.1 525 Or...', Object(React\SocketClient\SecureStream)) #1 /home/Dramiel/mamba/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Object(Closure), Array) #2 /home/Dramiel/mamba/vendor/react/socket-client/src/SecureStream.php(48): Evenement\EventEmitter->emit('data', Array) #3 [internal function]: React\SocketClient\SecureStream->handleData(Resource id #182, Object(React\EventLoop\StreamSelectLoop)) #4 /home/Dramiel/mamba/vendor/react/event-loop/src/StreamSelectLoop.php(232): call_user_func(Array, Resource id #182, Object(React\EventLoop\StreamSelectLoop)) #5 /home/Dramiel/mamba/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL) #6 /home/Dramiel/mamba/vendor/team-reflex/discord-php/src/Discord/Discord.php(1223): React\EventLoop\StreamSelectLoop->run() #7 /home/Dramiel/mamba/Dramiel.php(214): Discord\Discord->run() #8 {main} [] []
```

**Comment by davidcole1340** [comment]
@151 similar
