### ISSUE TITLE
getMessage not working

### ISSUE THREAD

**Issue by GreenSuslik** [teamreflex/DiscordPHP#171]
Here is my code.
```php
/**
 * @var Guild $guild ;
 */
$guild = $discord->guilds->get('id', '***');
$channel = $guild->channels->get('id', '***');
/**
 * @var Channel $channel
 */
$last_message_id = $channel->last_message_id;
$message = $channel->getMessage($last_message_id)->then(function ($message) {
    echo "Messages {$message->content}", PHP_EOL;
    exit(0);
})->otherwise(function ($reason) {
    echo "Error:" . $reason, PHP_EOL;
    exit(0);
});
```
When executed this error is al that appears
```
Error:Exception: Stream ended with incomplete control code in /var/www/devzone/discord-bot/vendor/react/http-client/src/ChunkedStreamDecoder.php:199
Stack trace:
#0 [internal function]: React\HttpClient\ChunkedStreamDecoder->handleEnd(Object(React\Stream\Stream))
#1 /var/www/devzone/discord-bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Array, Array)
#2 /var/www/devzone/discord-bot/vendor/react/stream/src/Stream.php(97): Evenement\EventEmitter->emit('end', Array)
#3 [internal function]: React\Stream\Stream->close(Object(React\Stream\Buffer))
#4 /var/www/devzone/discord-bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Array, Array)
#5 /var/www/devzone/discord-bot/vendor/react/stream/src/Buffer.php(71): Evenement\EventEmitter->emit('close', Array)
#6 /var/www/devzone/discord-bot/vendor/react/stream/src/Buffer.php(61): React\Stream\Buffer->close()
#7 /var/www/devzone/discord-bot/vendor/react/stream/src/Stream.php(119): React\Stream\Buffer->end(NULL)
#8 /var/www/devzone/discord-bot/vendor/react/stream/src/Stream.php(157): React\Stream\Stream->end()
#9 [internal function]: React\Stream\Stream->handleData(Resource id #206, Object(React\EventLoop\StreamSelectLoop))
#10 /var/www/devzone/discord-bot/vendor/react/event-loop/src/StreamSelectLoop.php(232): call_user_func(Array, Resource id #206, Object(React\EventLoop\StreamSelectLoop))
#11 /var/www/devzone/discord-bot/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(40684046.030045)
#12 /var/www/devzone/discord-bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(1228): React\EventLoop\StreamSelectLoop->run()
#13 /var/www/devzone/discord-bot/bot.php(125): Discord\Discord->run()
#14 {main}

Next RuntimeException: An error occurred in the underlying stream in /var/www/devzone/discord-bot/vendor/react/http-client/src/Response.php:90
Stack trace:
#0 [internal function]: React\HttpClient\Response->handleError(Object(Exception))
#1 /var/www/devzone/discord-bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Array, Array)
#2 /var/www/devzone/discord-bot/vendor/react/http-client/src/ChunkedStreamDecoder.php(199): React\HttpClient\ChunkedStreamDecoder->emit('error', Array)
#3 [internal function]: React\HttpClient\ChunkedStreamDecoder->handleEnd(Object(React\Stream\Stream))
#4 /var/www/devzone/discord-bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Array, Array)
#5 /var/www/devzone/discord-bot/vendor/react/stream/src/Stream.php(97): Evenement\EventEmitter->emit('end', Array)
#6 [internal function]: React\Stream\Stream->close(Object(React\Stream\Buffer))
#7 /var/www/devzone/discord-bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Array, Array)
#8 /var/www/devzone/discord-bot/vendor/react/stream/src/Buffer.php(71): Evenement\EventEmitter->emit('close', Array)
#9 /var/www/devzone/discord-bot/vendor/react/stream/src/Buffer.php(61): React\Stream\Buffer->close()
#10 /var/www/devzone/discord-bot/vendor/react/stream/src/Stream.php(119): React\Stream\Buffer->end(NULL)
#11 /var/www/devzone/discord-bot/vendor/react/stream/src/Stream.php(157): React\Stream\Stream->end()
#12 [internal function]: React\Stream\Stream->handleData(Resource id #206, Object(React\EventLoop\StreamSelectLoop))
#13 /var/www/devzone/discord-bot/vendor/react/event-loop/src/StreamSelectLoop.php(232): call_user_func(Array, Resource id #206, Object(React\EventLoop\StreamSelectLoop))
#14 /var/www/devzone/discord-bot/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(40684046.030045)
#15 /var/www/devzone/discord-bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(1228): React\EventLoop\StreamSelectLoop->run()
#16 /var/www/devzone/discord-bot/bot.php(125): Discord\Discord->run()
#17 {main}

Next RuntimeException: An error occured in the response in /var/www/devzone/discord-bot/vendor/react/http-client/src/Request.php:150
Stack trace:
#0 [internal function]: React\HttpClient\Request->React\HttpClient\{closure}(Object(RuntimeException), Object(React\HttpClient\Response))
#1 /var/www/devzone/discord-bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Object(Closure), Array)
#2 /var/www/devzone/discord-bot/vendor/react/http-client/src/Response.php(94): React\HttpClient\Response->emit('error', Array)
#3 [internal function]: React\HttpClient\Response->handleError(Object(Exception))
#4 /var/www/devzone/discord-bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Array, Array)
#5 /var/www/devzone/discord-bot/vendor/react/http-client/src/ChunkedStreamDecoder.php(199): React\HttpClient\ChunkedStreamDecoder->emit('error', Array)
#6 [internal function]: React\HttpClient\ChunkedStreamDecoder->handleEnd(Object(React\Stream\Stream))
#7 /var/www/devzone/discord-bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Array, Array)
#8 /var/www/devzone/discord-bot/vendor/react/stream/src/Stream.php(97): Evenement\EventEmitter->emit('end', Array)
#9 [internal function]: React\Stream\Stream->close(Object(React\Stream\Buffer))
#10 /var/www/devzone/discord-bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Array, Array)
#11 /var/www/devzone/discord-bot/vendor/react/stream/src/Buffer.php(71): Evenement\EventEmitter->emit('close', Array)
#12 /var/www/devzone/discord-bot/vendor/react/stream/src/Buffer.php(61): React\Stream\Buffer->close()
#13 /var/www/devzone/discord-bot/vendor/react/stream/src/Stream.php(119): React\Stream\Buffer->end(NULL)
#14 /var/www/devzone/discord-bot/vendor/react/stream/src/Stream.php(157): React\Stream\Stream->end()
#15 [internal function]: React\Stream\Stream->handleData(Resource id #206, Object(React\EventLoop\StreamSelectLoop))
#16 /var/www/devzone/discord-bot/vendor/react/event-loop/src/StreamSelectLoop.php(232): call_user_func(Array, Resource id #206, Object(React\EventLoop\StreamSelectLoop))
#17 /var/www/devzone/discord-bot/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(40684046.030045)
#18 /var/www/devzone/discord-bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(1228): React\EventLoop\StreamSelectLoop->run()
#19 /var/www/devzone/discord-bot/bot.php(125): Discord\Discord->run()
#20 {main}
```
I am update to the latest develop branch.

**Comment by uniquoooo** [comment]
Can you make sure `composer show | grep react/http-client` shows v0.4.14?

**Comment by GreenSuslik** [comment]
Yep!
```
react/http-client                    v0.4.14             Asynchronous HTTP client library.
wyrihaximus/react-guzzle-http-client 3.0.3               Asyncronous GuzzleRing adapter powered by react/http-client
wyrihaximus/react-guzzle-psr7        1.0.0               Asyncronous Guzzle (PSR7) adapter powered by react/http-client
```

**Comment by uniquoooo** [comment]
Could you try update to the latest develop branch and see if this still happens? @GreenSuslik

**Comment by GreenSuslik** [comment]
Hi! All done, it's work.
