### ISSUE TITLE
Few problems and questions with DiscordPHP And messages.

### ISSUE THREAD

**Issue by dyanakiev** [teamreflex/DiscordPHP#173]
Where is the problem?

```
<?php
include __DIR__.'/vendor/autoload.php';

use Discord\Discord;

use Discord\Parts\User\Game;

$discord = new Discord([
    'token' => 'secret opps :D'
]);

$game = $discord->factory(Game::class, [
    'name' => 'i am playing a game!',
]);

$discord->updatePresence($game);




```

When i run this code i get:
```
PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /srv/users/user01/other_apps/discordbot/vendor/team-reflex/discord-php/src/Discord/Discord.php:941
Stack trace:
#0 /srv/users/user01/other_apps/discordbot/vendor/team-reflex/discord-php/src/Discord/Discord.php(985): Discord\Discord->send(Array)
#1 /srv/users/user01/other_apps/discordbot/voice.php(16): Discord\Discord->updatePresence(Array)
#2 {main}
  thrown in /srv/users/user01/other_apps/discordbot/vendor/team-reflex/discord-php/src/Discord/Discord.php on line 941

Fatal error: Uncaught Error: Call to a member function send() on null in /srv/users/user01/other_apps/discordbot/vendor/team-reflex/discord-php/src/Discord/Discord.php:941
Stack trace:
#0 /srv/users/user01/other_apps/discordbot/vendor/team-reflex/discord-php/src/Discord/Discord.php(985): Discord\Discord->send(Array)
#1 /srv/users/user01/other_apps/discordbot/voice.php(16): Discord\Discord->updatePresence(Array)
#2 {main}
  thrown in /srv/users/user01/other_apps/discordbot/vendor/team-reflex/discord-php/src/Discord/Discord.php on line 941

```

**Comment by dyanakiev** [comment]
Oh ok i found solution! i have to put it in `$discord->on("ready", function ($discord) {});`

So i want to watch for messages how to do this? I want to do something like this:

```
while ($channelchating) {

if($channelchating[content] == '/rank') {
reply @$channelchating[user],  blah blah :D
}


}
```

**Comment by dyanakiev** [comment]
```
$discord->run();

$discord->close();
```

Why this not working?

**Comment by dyanakiev** [comment]
```
        $discord->on('ready', function ($discord) {
            $guild = $discord->guilds->get('id', 'xx');
            $channel = $guild->channels->get('id', 'xx');
            $channel->sendMessage('...');
            $discord->loop->addPeriodicTimer(1, function () use ($discord) {
                exit();
            });
        });
        $discord->run();
```
Is this okay? It works but..

**Comment by uniquoooo** [comment]
Most DiscordPHP functions use Promises because calls are async, this will be a better solution:
```php
$channel->sendMessage('...')->then(function ($message) {
    // do stuff when message is sent
    exit();
});
```

**Comment by davidcole1340** [comment]
I've just updated the develop branch to close the event loop by default when `$discord->close()` is run.
