### ISSUE TITLE
Call to a member function pull() on null (Websockets\Events\ChannelDelete.php)

### ISSUE THREAD

**Issue by Mista-Tea** [teamreflex/DiscordPHP#237]
I am using the `DiscordCommandClient` class to create some trivial commands and just listening on GUILD_MEMBER_ADD for new users.

At random, the app will crash with the following output:

```
Notice: Trying to get property of non-object in 
W:\discord\www\vendor\team-reflex\discord-php\src\Discord\WebSockets\Events\ChannelDelete.php
on line 28

Fatal error: Uncaught Error: Call to a member function pull() on null in 
W:\discord\www\vendor\team-reflex\discord-php\src\Discord\WebSockets\Events\ChannelDelete.php:28

Stack trace:
#0 W:\discord\www\vendor\team-reflex\discord-php\src\Discord\Discord.php(673): Discord\WebSockets\Events\ChannelDelete->handle(Object(React\Promise\Deferred), Object(stdClass))
#1 W:\discord\www\vendor\team-reflex\discord-php\src\Discord\Discord.php(564): Discord\Discord->handleDispatch(Object(stdClass))
#2 [internal function]: Discord\Discord->handleWsMessage(Object(Ratchet\RFC6455\Messaging\Message), Object(Ratchet\Client\WebSocket))
#3 W:\discord\www\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#4 W:\discord\www\vendor\ratchet\pawl\src\WebSocket.php(71): Ratchet\Client\WebSocket->emit('message', Array)
#5 W:\discord\www\vendor\ratchet\rfc6455\src\Messaging\MessageBuffer.php(104): Ratchet\Client\WebSocket->Ratchet\Client\{closure}(Object(Ratchet\RFC6455\Messaging\Message))
#6 W:\disc in W:\discord\www\vendor\team-reflex\discord-php\src\Discord\WebSockets\Events\ChannelDelete.php on line 28
```

No one in my Discord is deleting channels, so I'm not sure why the ChannelDelete event is even getting fired.

**Comment by AlphawolfWMP** [comment]
Same behaviour here, listening on GUILD_MEMBER_ADD.

**Comment by AlphawolfWMP** [comment]
As a workaround I'm using

    'disabledEvents' => [
	    'CHANNEL_DELETE'
    ]

which "solves" the issue for me.

**Comment by davidcole1340** [comment]
Interesting. Will need to try and reproduce. Possibly a DM channel being deleted but I'm not sure if that is even possible?

**Comment by davidcole1340** [comment]
Wasn't able to reproduce this but I have changed it so the event will check there is a valid guild before deleting.
