### ISSUE TITLE
[bot-api] Reply doesn't seems to work

### ISSUE THREAD

**Issue by Zexorz** [teamreflex/DiscordPHP#36]
Here's an error i get by using basic.php

```
Fatal error: Uncaught exception 'Discord\Exceptions\Rest\NotFoundException' with message 'Error code 404: This resource does not exist. NOT FOUND - {"message": ""} - channels/1.3916996587697E+17/messages' in \src\Discord\Helpers\Guzzle.php:191
Stack trace:
#0 src\Discord\Helpers\Guzzle.php(125): Discord\Helpers\Guzzle::handleError(404, 'NOT FOUND', Object(GuzzleHttp\Psr7\Stream), 'channels/1.3916...')
#1 src\Discord\Helpers\Guzzle.php(61): Discord\Helpers\Guzzle::runRequest('post', 'channels/1.3916...', Array, false, Array)
#2 src\Discord\Parts\Channel\Channel.php(303): Discord\Helpers\Guzzle::__callStatic('post', Array)
#3 src\Discord\Parts\Channel\Channel.php(303): Discord\Helpers\Guzzle::post('channels/1.3916...', Array)
```

**Comment by proxikal** [comment]
Getting the same thing.

**Comment by Zexorz** [comment]
Pratically saying, only 32bit PHP has this issue since discord channels has 64bit integers. 64bit PHP solves it, but its still a bug according to David

**Comment by uniquoooo** [comment]
For now, could you guys change back to JSON by doing:
```
$ws = new WebSocket($discord, null, false);
```

**Comment by proxikal** [comment]
that doesn't work for me. it causes an error **can't pass parameter 2 by reference**

**Comment by uniquoooo** [comment]
Ehh ok, could you try:
```
$loop = \React\EventLoop\Factory::create();
$ws = new WebSocket($discord, $loop, false);
```

**Comment by Zexorz** [comment]
@uniquoooo the last code you provided looks like its working on php 5.6.14 with Architecture => x86

**Comment by proxikal** [comment]
Ok it's running on PHP 7(64bit)

**Comment by uniquoooo** [comment]
No fix as far as I know, closing since I have implemented a check to see if the PHP install is 32-bit.
